import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";

// Importação dinâmica do componente CheckoutMercadoPago, desativando SSR
const PaymentMercadoPago = dynamic(() => import("@/components/PaymentMercadoPago"), {
    ssr: false,
});

const WalletMercadoPago = dynamic(() => import("@/components/WalletMercadoPago"), {
    ssr: false,
});

import UserTab from "@/components/User_Tab";
import Admin_Product_Creator from "@/components/Admin_Product_Creator";
import Admin_Product_List from "@/components/Admin_Product_List";
import Client_Product_List from "@/components/Client_Product_List";
import Client_Cart from "@/components/Client_Cart";
import Client_Checkout from "@/components/Client_Checkout";

export default function Home() {
    return (
        <>
            <Head>
                <title>Mercado Pago e Firebase no NEXT</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <h1 className="Website_Title">Mercado Pago e Firebase com NEXT</h1>
                {/* <PaymentMercadoPago /> */}
                <UserTab />
                <Admin_Product_List />
                <Client_Product_List />
                <Client_Cart />
                <Client_Checkout />
            </main>
        </>
    );
}
