import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";

// Importação dinâmica do componente CheckoutMercadoPago, desativando SSR
const PaymentMercadoPago = dynamic(() => import("@/components/PaymentMercadoPago"), {
    ssr: false,
});

const WalletMercadoPago = dynamic(() => import("@/components/WalletMercadoPago"), {
    ssr: false,
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Mercado Pago Wallet for NEXT JS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <h1>Mercado Pago Wallet for NEXT JS</h1>
                {/* <PaymentMercadoPago /> */}
                <WalletMercadoPago />
            </main>
        </>
    );
}
